### ISSUE TITLE
concurrentqueue is not listed as a dependency and is also not included

### ISSUE THREAD

**Issue by wolterhv** [lvella/glome#9]
In order to be able to build the program, I had to clone cameron314's concurrentqueue into `./external/concurrentqueue`

**Comment by lvella** [comment]
It is actually a git submodule. You have to run `git submodule update --init` in order to initialize it.

**Comment by lvella** [comment]
I've updated the README with the instructions. Resolved in commit d04f27f360799138a41b2dd976cf5eb1eec28f77.

**Comment by wolterhv** [comment]
Great!
